import { Component, inject } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { countryValidator } from '../../validators/registration-validators/registration-validators';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register-page',
  imports: [ReactiveFormsModule],
  templateUrl: './register-page.html',
  styleUrl: './register-page.css',
})

export class RegisterPage {
  formbuilder = inject(FormBuilder);

  router = inject(Router);

  registerForm: FormGroup = this.formbuilder.group({
      userName: ['', [
        Validators.required, 
        Validators.minLength(5),
        Validators.pattern('^[a-zA-Z ]+$') // Regex from Module 3 Practice Assignment 4
      ]],
      userEmail: ['', [
        Validators.required, 
        Validators.email
      ]],
      userPhone: ['', [
        Validators.required, 
        Validators.pattern('^[0-9]{10}$') // Regex generated by CoPilot
      ]],
      userDOB: ['', [
        Validators.required
      ]],
      userStreetAddress: ['', [
        Validators.required, 
        Validators.pattern('^[a-zA-Z0-9 ]+$') // Regex modifiedfrom Module 3 Practice Assignment 4
      ]],
      userProvince: ['', [
        Validators.required
      ]],
      userCountry: ['', [
        Validators.required,
        countryValidator('Canada')
      ]],
      userTerms: [false, [
        Validators.requiredTrue
      ]]
    });

    onSubmit() {
      if(this.registerForm.valid) {
        console.log('Registration submitted:', this.registerForm.value);
        alert('Thank you for registering, ' +
        this.registerForm.value.userName);
        this.registerForm.reset();
        this.router.navigate(['/products']);
      }
    }
}

